export const FeaturedBookItems = [
    {
        id: 1,
        img: '/images/FB1.jpg',
        href: '#',
        author: 'Ocean Vuong',
        title: 'Một thoáng ta rực rỡ giữa nhân gian',
        price: 135000,
    },
    {
        id: 2,
        img: '/images/FB2.jpg',
        href: '#',
        author: 'Morgan Housel',
        title: 'Tâm lý học về tiền',
        price: 189000,
    },
    {
        id: 3,
        img: '/images/FB3.jpg',
        href: '#',
        author: 'Diệp Hồng Vũ',
        title: 'Tâm lý học tội phạm - Phác họa chân dung kẻ phạm tội',
        price: 145000,
    },
    {
        id: 4,
        img: '/images/FB4.jpg',
        href: '#',
        author: 'Paul Coelho',
        title: 'Nhà giả kim',
        price: 79000,
    },
    {
        id: 5,
        img: '/images/FB5.jpg',
        href: '#',
        author: 'Cao Minh',
        title: 'Thiên tài bên trái kẻ điên bên phải',
        price: 179000,
    },
    {
        id: 6,
        img: '/images/FB6.jpg',
        href: '#',
        author: 'Lê Bảo Ngọc',
        title: 'Không phải sói nhưng cũng đừng là cừu',
        price: 128000,
    },
    {
        id: 7,
        img: '/images/FB7.jpg',
        href: '#',
        author: 'Shannon Thomas , LCSW',
        title: 'Thao túng tâm lý',
        price: 169000,
    },
    {
        id: 8,
        img: '/images/FB8.jpg',
        href: '#',
        author: 'Nguyễn Đoàn Minh Thư',
        title: 'Hành tinh của một kẻ nghĩ nhiều',
        price: 86000,
    },
];
